id: P010321
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6940
  title: ཆོས་སྤྱོད་ཕྱོགས་བསྒྲིགས་རཏྣའི་ཞལ་ལུང་།
  author: ''
  volumes:
    5dc8928f912e42aea64b5c07f3ec29c4:
      image_group_id: I3CN6942
      title: ''
      volume_number: 1
      total_pages: 587
      base_file: v001.txt
